### PR TITLE
Add boilerplate SvelteKit UI

### PR DESCRIPTION
**Pull request by ethanlook**

### CODE REVIEW

**Review by zaporter-work — APPROVED** [review]
LGTM!

**Comment by zaporter-work** [comment]
@ethanlook Trying to clean up my github inbox. Are you willing to either close or merge this?

**Comment by zaporter-work** [comment]
Oh shit -- ctrl+en

**Comment by ethanlook** [comment]
Closing - we should use SvelteKit v2 when the time comes

**Pull request closed without merging**
